### ISSUE TITLE
findForUser方法返回的应该是\Laravel\Passport\Client才对？

### ISSUE THREAD

**Issue by renkx** [overtrue/laravel-passport-cache-client#6]
![image](https://user-images.githubusercontent.com/26194193/147391044-a8c9632d-84df-4522-908c-a2cc19115fde.png)

https://github.com/overtrue/laravel-passport-cache-client/blob/976a75c6b57a4239ae9da6da262c674707c6a6c8/src/CacheClientRepository.php#L124

**Comment by overtrue** [comment]
CV 代码的锅 😭
