### ISSUE TITLE
缓存的key，$clientId和$userId有可能出现一样的ID，获取的缓存是否会出现问题

### ISSUE THREAD

**Issue by renkx** [overtrue/laravel-passport-cache-client#7]
如下图，如果$clientId和$userId的值都为1，有可能获取的缓存会异常
![image](https://user-images.githubusercontent.com/26194193/147391222-5c399b66-fb9b-422e-80a6-e261b1fd3763.png)

**Comment by overtrue** [comment]
抱歉，测试不足，已修复，感谢反馈。
